[package]
name = "xtask"
version = "0.3.0"
authors = ["mechiru <u9053u6d41@gmail.com>", "me@abdolence.dev"]
edition = "2021"

[dependencies]
tonic-build = { version = "0.7", features = ["prost-build"] }
prost-build = "0.10"
