[package]
name = "spanner-admin"
version = "0.1.0"
authors = ["mechiru <u9053u6d41@gmail.com>"]
edition = "2018"

[dependencies]
googapis = { path = "./../../googapis", default-features = false, features = ["google-spanner-admin-database-v1"] }
gouth = { version = "0.1" }
tonic = { version = "0.3", features = ["tls"] }
prost = { version = "0.6" }
prost-types = { version = "0.6" }
tokio = { version = "0.2", features = ["rt-threaded", "time", "stream", "fs", "macros", "uds"] }
